import { useState, useRef } from "react";
import { useStudy } from "@/context/StudyContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { Upload as UploadIcon, FileText, CheckCircle, Loader2 } from "lucide-react";

const UploadPage = () => {
  const [file, setFile] = useState<File | null>(null);
  const [subject, setSubject] = useState("");
  const [examDate, setExamDate] = useState("");
  const [weeks, setWeeks] = useState("4");
  const [uploading, setUploading] = useState(false);
  const [success, setSuccess] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const { addSubject } = useStudy();
  const { toast } = useToast();

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    const f = e.dataTransfer.files[0];
    if (f && (f.type === "application/pdf" || f.name.endsWith(".docx"))) setFile(f);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file || !subject || !examDate) {
      toast({ title: "Missing fields", description: "Please fill in all required fields.", variant: "destructive" });
      return;
    }
    setUploading(true);
    // Simulate AI processing
    await new Promise((r) => setTimeout(r, 3000));
    addSubject({
      id: String(Date.now()),
      name: subject,
      examDate,
      progress: 0,
      totalCards: Math.floor(Math.random() * 40 + 20),
      totalMcqs: Math.floor(Math.random() * 20 + 15),
      uploadedAt: new Date().toISOString().split("T")[0],
    });
    setUploading(false);
    setSuccess(true);
    toast({ title: "Notes uploaded!", description: "AI is generating your study materials." });
  };

  if (success) {
    return (
      <div className="flex flex-col items-center justify-center py-20 animate-fade-in">
        <CheckCircle className="h-16 w-16 text-accent mb-4" />
        <h2 className="text-2xl font-bold mb-2">Upload Successful!</h2>
        <p className="text-muted-foreground mb-6">Your study materials are being generated by AI.</p>
        <Button onClick={() => { setSuccess(false); setFile(null); setSubject(""); setExamDate(""); }}>Upload Another</Button>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto animate-fade-in">
      <h1 className="text-2xl font-bold mb-2">Upload Notes</h1>
      <p className="text-muted-foreground mb-8">Upload your study materials and let AI create your revision plan.</p>

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Drop zone */}
        <div
          onDragOver={(e) => e.preventDefault()}
          onDrop={handleDrop}
          onClick={() => inputRef.current?.click()}
          className="flex flex-col items-center justify-center rounded-xl border-2 border-dashed border-border bg-muted/30 p-10 cursor-pointer hover:border-primary/50 transition-colors"
        >
          {file ? (
            <div className="flex items-center gap-3">
              <FileText className="h-8 w-8 text-primary" />
              <div>
                <p className="font-medium">{file.name}</p>
                <p className="text-sm text-muted-foreground">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
              </div>
            </div>
          ) : (
            <>
              <UploadIcon className="h-10 w-10 text-muted-foreground mb-3" />
              <p className="font-medium">Drag & drop your file here</p>
              <p className="text-sm text-muted-foreground">or click to browse (PDF, DOCX)</p>
            </>
          )}
          <input ref={inputRef} type="file" accept=".pdf,.docx" className="hidden" onChange={(e) => e.target.files?.[0] && setFile(e.target.files[0])} />
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-2">
            <Label>Subject Name</Label>
            <Input placeholder="e.g. Machine Learning" value={subject} onChange={(e) => setSubject(e.target.value)} />
          </div>
          <div className="space-y-2">
            <Label>Exam Date</Label>
            <Input type="date" value={examDate} onChange={(e) => setExamDate(e.target.value)} />
          </div>
        </div>

        <div className="space-y-2">
          <Label>Study Duration (weeks)</Label>
          <Input type="number" min="1" max="52" value={weeks} onChange={(e) => setWeeks(e.target.value)} />
        </div>

        <Button type="submit" className="w-full" disabled={uploading}>
          {uploading ? (
            <span className="flex items-center gap-2"><Loader2 className="h-4 w-4 animate-spin" /> Processing with AI…</span>
          ) : (
            "Upload & Generate Study Plan"
          )}
        </Button>
      </form>
    </div>
  );
};

export default UploadPage;
